config:
  lite:
    enabled: true
    routes:
      - host: 6f11c9c9e374.instantmc.gg
        backend:  127.0.0.1:25567
      - host: fb7f8e9cca14.instantmc.gg
        backend:  127.0.0.1:25568
      - host: 79d974e19494.instantmc.gg
        backend:  127.0.0.1:25569
      - host: a26eda66c816.instantmc.gg
        backend:  127.0.0.1:25570
      - host: ad1bd64cf909.instantmc.gg
        backend:  127.0.0.1:25571
      - host: 206e8c30d1ff.instantmc.gg
        backend:  127.0.0.1:25572
      - host: 84efd4bd7c77.instantmc.gg
        backend:  127.0.0.1:25573
      - host: 08fd9dcb8efa.instantmc.gg
        backend:  127.0.0.1:25574
      - host: 11d2d76aa7a5.instantmc.gg
        backend:  127.0.0.1:25575