version: "3.9"

services:
  gate:
    image: ghcr.io/minekube/gate:latest
    container_name: gate
    command: /gate --config /config/config.yml
    restart: always
    network_mode: host
    volumes:
      - ./config:/config
